import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { GenerateOptions } from "../types.js";
import { renderServerCode } from "./templates.js";

export async function generate(opts: GenerateOptions): Promise<void> {
	mkdirSync(opts.outputDir, { recursive: true });
	mkdirSync(join(opts.outputDir, "src"), { recursive: true });

	writeFileSync(join(opts.outputDir, "src", "server.ts"), renderServerCode(opts));

	writeFileSync(
		join(opts.outputDir, "package.json"),
		JSON.stringify(
			{
				name: slugify(opts.serverName),
				version: "0.1.0",
				type: "module",
				scripts: {
					build: "tsc",
					start: "node dist/server.js",
				},
				dependencies: {
					"@modelcontextprotocol/sdk": "^1.29.0",
					zod: "^3.23.0",
				},
				devDependencies: {
					typescript: "^5.7.0",
					"@types/node": "^22.0.0",
				},
			},
			null,
			2,
		),
	);

	writeFileSync(
		join(opts.outputDir, "tsconfig.json"),
		JSON.stringify(
			{
				compilerOptions: {
					target: "ES2022",
					module: "Node16",
					moduleResolution: "Node16",
					outDir: "dist",
					rootDir: "src",
					strict: true,
					esModuleInterop: true,
					skipLibCheck: true,
					declaration: true,
				},
				include: ["src/**/*"],
			},
			null,
			2,
		),
	);

	writeFileSync(
		join(opts.outputDir, ".env.example"),
		generateEnvExample(opts),
	);
}

function slugify(name: string): string {
	return name
		.toLowerCase()
		.replace(/[^a-z0-9]+/g, "-")
		.replace(/^-|-$/g, "");
}

function generateEnvExample(opts: GenerateOptions): string {
	const lines = ["# Generated by openapi-to-mcp", ""];
	const server = opts.spec.servers?.[0];
	lines.push(`API_BASE_URL=${server?.url ?? "https://api.example.com"}`);

	if (opts.auth === "api-key") {
		lines.push("API_KEY=your-api-key-here");
	} else if (opts.auth === "bearer") {
		lines.push("API_TOKEN=your-bearer-token-here");
	} else if (opts.auth === "oauth2") {
		lines.push("OAUTH_CLIENT_ID=");
		lines.push("OAUTH_CLIENT_SECRET=");
		lines.push("OAUTH_TOKEN_URL=");
	}

	return lines.join("\n") + "\n";
}
